### ISSUE TITLE
Be clear about non-colour opts given to bemenu

### ISSUE THREAD

**Issue by sidju** [catppuccin/bemenu#3]
It would be nice to either not include `-i -l 20` or be clear about what it does.

(Optional, since there is a --help option for bemenu-run that explains it well.)

**Comment by iruzo** [comment]
Hi !,

Thanks for opening the issue !, discussing with the community about changing more things than the color palette when porting an app, we reach to the conclusion that we should stick to the colors when creating a theme for an application.

Following that, I have removed those parameters from the port.

Thanks a lot !

**Comment by iruzo** [comment]
Hi !,

Thanks for opening the issue !, discussing with the community about changing more things than the color palette when porting an app, we reach to the conclusion that we should stick to the colors when creating a theme for an application.

Following that, I have removed those parameters from the port.

Thanks a lot !
